Add .py script to validate json tags in Go files

diff --git a/.github/workflows/staticAnalysis.yml b/.github/workflows/staticAnalysis.yml
--- a/.github/workflows/staticAnalysis.yml
+++ b/.github/workflows/staticAnalysis.yml
@@ -50,5 +50,8 @@ jobs:
           go get -u gitlab.com/opennota/check/cmd/aligncheck@latest
           aligncheck ./... || echo "aligncheck detected inefficiently packed structs"
 
-      - name: Check yaml field names format
+      - name: Check yaml field names and yaml tags
         run: tools/validate/validateYaml.py || echo "invalid yaml field name(s) detected"
+
+      - name: Check json tags
+        run: tools/validate/validateJson.py || echo "invalid json tag(s) detected"
